### ISSUE TITLE
Grouped enumerators in a module followed by public subroutines

### ISSUE THREAD

**Issue by william-dawson** [hansec/fortran-language-server#74]
Consider the following example:

```
MODULE EnumMod
  IMPLICIT NONE
  ENUM, BIND(C)
     ENUMERATOR :: Apple = 1 
     ENUMERATOR :: Pear = 2 
  END ENUM
  PUBLIC :: TestRoutine
CONTAINS
  SUBROUTINE TestRoutine
     WRITE(*,*) Apple
  END SUBROUTINE TestRoutine
END MODULE
```

Using the command:
`fortls  --debug_parser --debug_filepath EnumMod.f90`

I get the report:
```
MODULE EnumMod !!! MODULE statement(1)
END ENUM !!! END "ENUM" scope(6)
Traceback (most recent call last):
  File "/usr/local/bin/fortls", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fortls/__init__.py", line 137, in main
    ast_new = process_file(contents_split, True, fixed_format=fixed_flag, debug=True)
  File "/usr/local/lib/python3.7/site-packages/fortls/parse_fortran.py", line 852, in process_file
    file_obj.add_public(word)
  File "/usr/local/lib/python3.7/site-packages/fortls/objects.py", line 1094, in add_public
    self.public_list.append(self.enc_scope_name+'::'+name)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Note that if you delete the line:
`PUBLIC :: TestRoutine`

There is no longer an issue. I can also move that line to before the enum and it works. So it seems like most of the enum support is working great, but if you could make this small fix I'd appreciate it. Thanks!

**Comment by hansec** [comment]
Thanks for the report! I just pushed a fix to this issue that will be included in the next patch (probably later today).

**Comment by william-dawson** [comment]
Fantastic, thanks so much!
