### ISSUE TITLE
support for operator overloading

### ISSUE THREAD

**Issue by emanspeaks** [hansec/fortran-language-server#79]
The following sample code block fails to parse correctly:

```fortran
 module string_utilities
    implicit none
    private
    interface to_unicode
        module procedure to_uni, to_uni_vec
    end interface
    interface operator(//)
       module procedure ucs4_join_default, default_join_ucs4
    end interface
    public :: operator(//)
end module string_utilities
```

Results in the following debug output: 
```

Testing parser
  File = "Untitled-3.f90"
  Detected format: free

=========
Parser Output
=========

module string_utilities !!! MODULE statement(1)
private !!! Visiblity statement(3)
interface to_unicode !!! INTERFACE statement(4)
module procedure to_uni, to_uni_vec !!! INTERFACE-PRO statement(5)
end interface !!! END "INTERFACE" scope(6)
end interface !!! END "INTERFACE" scope(9)
Traceback (most recent call last):
  File "c:\miniconda\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\miniconda\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\miniconda\miniconda3\Scripts\fortls.exe\__main__.py", line 9, in <module>
  File "c:\miniconda\miniconda3\lib\site-packages\fortls\__init__.py", line 137, in main
    ast_new = process_file(contents_split, True, fixed_format=fixed_flag, debug=True)
  File "c:\miniconda\miniconda3\lib\site-packages\fortls\parse_fortran.py", line 869, in process_file
    file_obj.add_public(word)
  File "c:\miniconda\miniconda3\lib\site-packages\fortls\objects.py", line 1105, in add_public
    self.public_list.append(self.enc_scope_name+'::'+name)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

This appears to me to be caused by not recognizing operator overloading correctly.

**Comment by hansec** [comment]
Thanks for the report. This should now be fixed in master and will be included in the next patch.
